{{ if .Values.gremlin.installK8sClient }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chao
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "gremlin.commonLabels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gremlin-watcher
  labels:
    {{- include "gremlin.commonLabels" . | indent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["replicasets", "deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chao
  labels:
    {{- include "gremlin.commonLabels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: chao
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gremlin-watcher
{{ end }}
